title: Portfolio
author:
  name: Justin Ong
  email: justinongzhenze@gmail.com
title: Justin Ong
logo: /assets/img/pfp.png
description: Developer/Artist/Creator
show_downloads: false
theme: minima
minima:
  skin: dark
