title: Portfolio
author:
  name: Justin Ong
  email: justinongzhenze@gmail.com

description: Developer/Artist/Creator
show_downloads: false

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: dark