title: Portfolio
author:
  name: Justin Ong
  email: justinongzhenze@gmail.com

description: Developer/Artist/Creator
show_downloads: false

remote_theme: jekyll/minima

header_pages:

minima:
  skin: solarized-dark

social_links:
- { platform: github,         user_url: "https://github.com/aJustinOng" }
- { platform: linkedin,       user_url: "https://www.linkedin.com/in/a-justin-ong" }
- { platform: instagram,      user_url: "https://www.instagram.com/idrawshizzle" }